/* Local edit server: serves the static site (with video range support) AND
   accepts POST /api/save to write data/trip.js. 127.0.0.1 only — never exposed.
   Run:  node edit-server.js [port]   (launch.json config "roadtrip").
   To go PUBLIC: revert the "roadtrip" launch config to python http.server and
   delete editor.js / editor.css (see NOTES.md). */
const http = require("http");
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const PORT = parseInt(process.argv[2] || "4640", 10);
const MIME = {
  ".html": "text/html; charset=utf-8", ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8", ".json": "application/json",
  ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".gif": "image/gif",
  ".webp": "image/webp", ".svg": "image/svg+xml", ".mp4": "video/mp4", ".mov": "video/quicktime",
  ".m4v": "video/x-m4v", ".woff2": "font/woff2", ".woff": "font/woff", ".txt": "text/plain; charset=utf-8"
};

function safePath(url) {
  let p = decodeURIComponent(url.split("?")[0]);
  if (p === "/") p = "/index.html";
  const full = path.normalize(path.join(ROOT, p));
  return full.startsWith(ROOT) ? full : null;       // block path traversal
}

const server = http.createServer((req, res) => {
  // ---- save endpoint ----
  if (req.method === "POST" && req.url.split("?")[0] === "/api/save") {
    let body = "";
    req.on("data", (c) => { body += c; if (body.length > 80e6) req.destroy(); });
    req.on("end", () => {
      try {
        const data = JSON.parse(body);
        const out = "/* GENERATED by the editor (Save). Safe to hand-edit. */\nwindow.TRIP = " +
                    JSON.stringify(data, null, 2) + ";\n";
        const target = path.join(ROOT, "data", "trip.js");
        try {                                          // timestamped backup before overwrite
          const bdir = path.join(ROOT, "data", "_backups");
          fs.mkdirSync(bdir, { recursive: true });
          if (fs.existsSync(target)) fs.copyFileSync(target, path.join(bdir, "trip-" + Date.now() + ".js"));
        } catch (e) {}
        fs.writeFileSync(target, out);
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ ok: true }));
      } catch (e) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ ok: false, error: String(e && e.message || e) }));
      }
    });
    return;
  }
  // ---- static files (with range for video seeking) ----
  const full = safePath(req.url);
  if (!full) { res.writeHead(403); res.end("forbidden"); return; }
  fs.stat(full, (err, st) => {
    if (err || !st.isFile()) { res.writeHead(404); res.end("not found"); return; }
    const type = MIME[path.extname(full).toLowerCase()] || "application/octet-stream";
    const range = req.headers.range;
    if (range && /^bytes=/.test(range)) {
      const m = range.replace("bytes=", "").split("-");
      const start = parseInt(m[0], 10) || 0;
      const end = m[1] ? parseInt(m[1], 10) : st.size - 1;
      if (start > end || end >= st.size) { res.writeHead(416, { "Content-Range": "bytes */" + st.size }); res.end(); return; }
      res.writeHead(206, { "Content-Type": type, "Content-Range": "bytes " + start + "-" + end + "/" + st.size,
                           "Accept-Ranges": "bytes", "Content-Length": end - start + 1 });
      fs.createReadStream(full, { start, end }).pipe(res);
    } else {
      res.writeHead(200, { "Content-Type": type, "Content-Length": st.size, "Accept-Ranges": "bytes", "Cache-Control": "no-cache" });
      fs.createReadStream(full).pipe(res);
    }
  });
});
server.listen(PORT, "127.0.0.1", () => console.log("edit-server → http://127.0.0.1:" + PORT + "  (edit at /?edit=1)"));
